### PR TITLE
Updating R CMD check Actions

### PR DESCRIPTION
**Pull request by MowahidLatif**
Please wait until confirmation of merger. Waiting for proper checks to pass. Referencing previous errors with current errors for proper diagnoses of issue.

### CODE REVIEW

**Comment by MowahidLatif** [comment]
Please merge this branch. Everything is in order.

**Review by aylapear — CHANGES_REQUESTED** [review]
Can you reorder the badges to be CRAN, R-CMD, stable, codecov, license. Put the badge start and end syntax around all of the badges. 

Also the incorrect action template was run for this one. Try running the other templates until the operating system/R version match up better. This one is confusing because it is a CRAN package but it has less checks on it because it is a package we are actively trying to take off of CRAN.

**Review by aylapear — CHANGES_REQUESTED** [review]
Switch schedule back to 0 not *

Fix badges

**Comment by MowahidLatif** [comment]
Please merge this branch. Everything is in order.

**Pull request closed without merging**
