### PR TITLE
Upkeep

### PR DESCRIPTION
**Pull request by dunkenwg**

### CODE REVIEW

**Comment by dunkenwg** [comment]
Two code chunks in the README threw errors because of the classes of the data columns that were being checked. We could change the classes and filter values out of the data before running the checks if you'd prefer

**Comment by joethorley** [comment]
I wonder if this package couldn't be archived. Does anything depend on it?

**Comment by dunkenwg** [comment]
It doesn't look like any packages depend on it. Check out [this search on GitHub](https://github.com/search?q=org%3Apoissonconsulting+datacheckr+NOT+repo%3Apoissonconsulting%2Fdatacheckr++NOT+is%3Aarchived&type=code)

**Comment by dunkenwg** [comment]
If we're not going to archive this package you should take a look at the tests that I changed. Because of the way NULLs are handled by `check_vector()`, it was giving different error messages. Also we're getting a bunch of `S3 method error_set.character needs @export or @exportS3method tag.` when trying to check/document this package.

**Comment by joethorley** [comment]
Yes let's wait for @aylapear 's input but I'm thinking we should archive.

**Comment by aylapear** [comment]
I am in favour of archiving it. It isn't even loaded in `poispkgs` so I doubt anyone is using it and looks like an older version of chk and chktemplate type packages.

**Comment by joethorley** [comment]
OK I'm going to archive

**Pull request closed without merging**
